version: '3.4'

services:
  freakyfashionservices.basket:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  freakyfashionservices.catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  feakyfashion.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  freakyfashion.order:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  freakyfashion.productprice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

