version: '3.4'

services:
  freakyfashionservices.basket:
    image: ${DOCKER_REGISTRY-}freakyfashionservicesbasket
    build:
      context: .
      dockerfile: FreakyFashionServices.Basket/Dockerfile
    ports:
    - 55033:80
  redis:
    image: redis
  freakyfashionservices.catalog:
    image: ${DOCKER_REGISTRY-}freakyfashionservicescatalog
    build:
      context: .
      dockerfile: FreakyFashionServices.Catalog/Dockerfile


  feakyfashion.gateway:
    image: ${DOCKER_REGISTRY-}feakyfashiongateway
    build:
      context: .
      dockerfile: FeakyFashion.Gateway/Dockerfile
    ports:
    - 55020:80


  freakyfashion.order:
    image: ${DOCKER_REGISTRY-}freakyfashionorder
    build:
      context: .
      dockerfile: FreakyFashion.Order/Dockerfile


  freakyfashion.productprice:
    image: ${DOCKER_REGISTRY-}freakyfashionproductprice
    build:
      context: .
      dockerfile: FreakyFashion.ProductPrice/Dockerfile

